# Generated by Django 2.1.7 on 2019-04-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190405_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-update',)},
        ),
    ]
