# Generated by Django 2.1.7 on 2019-04-07 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20190406_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='user_list',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
