# Generated by Django 2.1.7 on 2019-04-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_user_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='user_list',
            new_name='users_like',
        ),
    ]
