# Generated by Django 2.1.7 on 2019-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190407_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
